---
apiVersion: v1
kind: Service
metadata:
  name: account-database
  labels:
    app: office-space
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: office-space
    tier: database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-database
  labels:
    app: office-space
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
        app: office-space
  template:
    metadata:
      labels:
        app: office-space
    spec:
      containers:
        - image: mysql:5.6
          name: account-database
          env:
            - name: MYSQL_USER
              value: michaelbolton
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: dockercon2017

          ports:
            - containerPort: 3306
              name: db
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
            claimName: mysql-pv-claim
